services:
  tasktracker:
    build: .
    container_name: tasktracker
    ports:
      - "5055:8080"          # useful for local testing
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=host.docker.internal;Database=TaskTracker;User Id=tasktracker_app;Password=${DB_PASSWORD};MultipleActiveResultSets=true;TrustServerCertificate=true
    volumes:
      - ./data/log:/app/data/log
    restart: unless-stopped
    networks:
      - whitent-umbraco

networks:
  whitent-umbraco:
    external: true